modLoader="javafml"
loaderVersion="[2,)"
license="Not specified"

[[mods]]
modId="sotv"
version="1.0.0"
displayName="SandsOfTheVoid"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="SANGEETH, MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.sotv]]
    modId="neoforge"
    type="required"
    versionRange="[20.4.223,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.sotv]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.4]"
    ordering="NONE"
    side="BOTH"




[[mixins]]
    config="mixins.sotv.json"